[env:uno]
platform = atmelavr
board = uno
framework = arduino
upload_protocol = custom
upload_command = avrdude -C /root/.platformio/packages/tool-avrdude/avrdude.conf -p atmega328p -c arduino -P net:ESP_IP:328 -b 115200 -U flash:w:$SOURCE:i
